name: "EasyCode Deploy"

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

    steps:
      - name: Working dir
        id: step_1
        run: echo "my_variable=Helo world" >> GITHUB_OUTPUT

      - name: Obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"

  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    env:
      SALIDA: ${{ needs.first_job.outputs.salida }}
      #interpolaci√≥n de variables de entorno

    steps:
      - name: Hello again
        run: echo "Hello again ${{ github.ref }}"
